name: Deploy Static Site to Azure Web App    
    
on:    
  push:    
    branches:    
      - main    
  workflow_dispatch:    
    
jobs:    
  deploy:    
    runs-on: ubuntu-latest    
    
    steps:    
      - uses: actions/checkout@v4    
    
      - name: Set up Node.js    
        uses: actions/setup-node@v3    
        with:    
          node-version: '16' # or use another version if required    
    
      - name: Install Azure CLI    
        uses: azure/setup-azure@v2    
    
      - name: Deploy to Azure Web App    
        id: deploy-to-webapp    
        uses: azure/webapps-deploy@v3    
        with:    
          app-name: 'collibrahome'    
          slot-name: 'devhomecollibra'    
          package: './' # Pointing to the root directory    
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BAA3E734D767487FB4E28AE9CCA81244 }}    
